# -*- coding: utf-8 -*-
"""alarm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1BK2NTAGKxzJ3WQ7KD5GPenypFCldk9
"""

from datetime import datetime
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError
import random
import time # Import time for sleep

def checker(a):
    while True:
        try:
            # Corrected 'toronto' to 'Toronto' for proper ZoneInfo lookup
            exact_time = datetime.now(ZoneInfo("America/Toronto"))
            n = exact_time.strftime('%H:%M')
            if n == a:
                print("Alarm!")
                print("\a" * 5)
                break
            else:
                pass
        except ZoneInfoNotFoundError:
            print("Error: Timezone 'America/Toronto' not found. Please ensure it's a valid IANA timezone name.")
            break # Exit checker if timezone is not found
        except Exception as e:
            print(f'An error occurred in checker: {e}')
            break # Exit on other errors
        time.sleep(1) # Wait for 1 second before checking again to avoid busy-waiting

def Clock():
    j = random.randint(1, 9999)
    print(f"welcome, as a guest the number {j} has been assigned to you")
    try:
        user_input = input("type in a time for the alarm (e.g., 8:39 or 08:39):")
        # Normalize user input to HH:MM format with leading zeros
        # This handles cases like '8:39' becoming '08:39'
        a = datetime.strptime(user_input, '%H:%M').strftime('%I:%M')
        checker(a)
    except ValueError:
        print("Invalid time format. Please use HH:MM (e.g., 8:39 or 08:39).")
        return Clock() # Recursively call to get valid input
    except KeyboardInterrupt:
        print(f"bye user {j}")
    except Exception as e:
        print(f'An unexpected error occurred in Clock: {e}')